(()=>{
  if(!location.pathname.endsWith('/app.html')) return;
  const API=(window.UC_BACKEND_URL||localStorage.getItem('uc-backend-url')||(location.hostname.endsWith('vercel.app')?location.origin:'')).replace(/\/$/,'');
  const TOKEN='uc-cloud-token',USER='uc-cloud-user';
  let token=localStorage.getItem(TOKEN)||'', user=null, nearby=[];
  try{user=JSON.parse(localStorage.getItem(USER)||'null')}catch(e){}
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const headers=()=>({'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})});
  async function api(path,opt={}){if(!API)throw new Error('Cloud backend is not connected yet.');const r=await fetch(API+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw new Error(j.error||'Cloud request failed');return j}
  function saveSession(j){token=j.token;user=j.user;localStorage.setItem(TOKEN,token);localStorage.setItem(USER,JSON.stringify(user));renderAccount()}
  async function ensureSession(){if(token)return true;try{saveSession(await api('/api/auth',{method:'POST',body:JSON.stringify({action:'guest'})}));return true}catch(e){return false}}
  function addAccountUI(){const profile=document.querySelectorAll('.screen')[4];if(!profile||document.getElementById('cloudAccount'))return;const box=document.createElement('div');box.className='card';box.id='cloudAccount';box.innerHTML='<div class="row"><div><b>Cloud account</b><div class="muted" id="cloudState">Checking…</div></div><button class="btn" id="cloudAccountBtn">Account</button></div><div id="cloudForm" class="hidden" style="margin-top:12px"><input id="cloudEmail" type="email" placeholder="Email" style="width:100%;padding:11px;border-radius:12px;border:1px solid #49384f;background:#0f0c12;color:#fff;margin-bottom:8px"><input id="cloudPass" type="password" placeholder="Password (6+ characters)" style="width:100%;padding:11px;border-radius:12px;border:1px solid #49384f;background:#0f0c12;color:#fff"><div class="actions"><button class="btn primary" id="cloudLogin">Sign in</button><button class="btn" id="cloudRegister">Create account</button></div></div>';profile.appendChild(box);document.getElementById('cloudAccountBtn').onclick=()=>document.getElementById('cloudForm').classList.toggle('hidden');document.getElementById('cloudLogin').onclick=()=>auth('login');document.getElementById('cloudRegister').onclick=()=>auth('register');renderAccount()}
  function renderAccount(){const s=document.getElementById('cloudState');if(!s)return;if(!API)s.textContent='Backend code ready · deployment connection pending';else if(user?.kind==='account')s.textContent='Signed in · '+(user.email||'account');else if(token)s.textContent='Guest cloud session active';else s.textContent='Not signed in'}
  async function auth(action){const email=document.getElementById('cloudEmail').value.trim(),password=document.getElementById('cloudPass').value;try{saveSession(await api('/api/auth',{method:'POST',body:JSON.stringify({action,email,password})}));document.getElementById('cloudForm').classList.add('hidden');await pushProfile();toast(action==='register'?'Account created':'Signed in')}catch(e){toast(e.message)}}
  async function pushProfile(){if(!token)return;try{await api('/api/profile',{method:'PUT',body:JSON.stringify({profile:{...p,status:localStorage.getItem('uc-cue')||p.status,cueIn:{...(p.cueIn||{}),active:localStorage.getItem('uc-cuein')==='1'}}})})}catch(e){}}
  async function syncPresence(){if(!token)return;const active=localStorage.getItem('uc-cuein')==='1',venue=p.cueIn?.venue||'',status=localStorage.getItem('uc-cue')||p.status||'available';try{await api('/api/presence',{method:'POST',body:JSON.stringify({active,venue,status})})}catch(e){}}
  async function loadNearby(){const box=document.querySelectorAll('.screen')[1]?.querySelector('.empty');if(!box)return;if(!API||!token){box.textContent='Cloud Nearby is ready but the hosted backend is not connected yet.';return}const venue=p.cueIn?.venue||'';if(localStorage.getItem('uc-cuein')!=='1'){box.textContent='Cue-In to see real people at your location.';return}try{const j=await api('/api/presence?venue='+encodeURIComponent(venue));nearby=j.people||[];if(!nearby.length){box.innerHTML='No other Cue’d-In people here yet.';return}box.innerHTML=nearby.map((x,i)=>'<div class="person" style="text-align:left;margin-bottom:8px"><div class="row"><div><b>'+esc(x.name||'Unspoken Cues user')+'</b><div class="muted">'+esc(x.presence?.status||x.status||'')+' · '+esc(x.presence?.venue||venue)+'</div></div></div><div class="actions"><button class="btn" data-compat="'+i+'">Compatibility</button><button class="btn primary" data-interest="'+i+'">Interested</button><button class="btn" data-maybe="'+i+'">Maybe</button></div></div>').join('');box.querySelectorAll('[data-compat]').forEach(b=>b.onclick=()=>compat(nearby[+b.dataset.compat]));box.querySelectorAll('[data-interest]').forEach(b=>b.onclick=()=>mutual(nearby[+b.dataset.interest],'interested'));box.querySelectorAll('[data-maybe]').forEach(b=>b.onclick=()=>mutual(nearby[+b.dataset.maybe],'maybe'))}catch(e){box.textContent=e.message}}
  async function compat(other){try{const j=await api('/api/compatibility',{method:'POST',body:JSON.stringify({me:{...p,status:localStorage.getItem('uc-cue')||p.status},them:other})});toast((j.level||'Compatibility')+' · '+j.score+'%')}catch(e){toast(e.message)}}
  async function mutual(other,answer){try{const j=await api('/api/mutual',{method:'POST',body:JSON.stringify({targetId:other.id,answer})});toast(j.message)}catch(e){toast(e.message)}}
  async function cloudBinder(){if(!token)return null;try{return (await api('/api/binder')).cards||[]}catch(e){return null}}
  async function migrateBinder(){if(!token)return;let local=[];try{local=JSON.parse(localStorage.getItem('swap-binder-v5')||'[]')}catch(e){}for(const card of local){try{await api('/api/binder',{method:'POST',body:JSON.stringify({card})})}catch(e){}}}
  function hook(){const oldCue=cueIn;cueIn=function(){oldCue();syncPresence();pushProfile();setTimeout(loadNearby,100)};const oldSet=setCue;setCue=function(s){oldSet(s);syncPresence();pushProfile()};const oldGo=go;go=function(i){oldGo(i);if(i===1)loadNearby();if(i===3)renderCloudBinder()}}
  async function renderCloudBinder(){const cards=await cloudBinder();if(cards===null)return;if(!cards.length){document.getElementById('collection').innerHTML='<div class="empty">No cloud cards collected yet.</div>';return}document.getElementById('collection').innerHTML=cards.map(x=>'<div class="collectCard">'+(x.cardImage?'<img src="'+esc(x.cardImage)+'" alt="S.W.A.P. card">':'')+'<b>'+esc(x.name||x.cardTitle||'S.W.A.P. Card')+'</b><div class="muted">'+esc(x.cardNumber||'')+'</div></div>').join('')}
  async function start(){addAccountUI();if(!API){renderAccount();return}await ensureSession();await pushProfile();await migrateBinder();await syncPresence();renderAccount();if(current===1)loadNearby();if(current===3)renderCloudBinder()}
  hook();start();
})();
