plugins {
    id 'com.android.application'
}

android {
    namespace 'com.unspokencues.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.unspokencues.mobile'
        minSdk 26
        targetSdk 35
        versionCode 26
        versionName '4.0.0-phone'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-wearable:19.0.0'
}
